config/routes.rb
Sightings::Application.routes.draw do
  root :to => "home#index"
  get "home/index"

  resources :sightings

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  belongs_to :sighting
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :sighting_type
  has_one :location
  attr_accessible :comment, :date, :description, :sighter, :sighting_type, :sighting_type_id, :location_attributes
  accepts_nested_attributes_for :location
end

app/models/sighting_type.rb
class SightingType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to sightings_url
  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  def index
    @sightings = Sighting.all
  end

  def new
    @sighting = Sighting.new
    @sighting.location = Location.new
  end

  def create
    @sighting = Sighting.new(params[:sighting])

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to(@sighting,
                                  :notice => 'Sighting was successfully created.') }
        format.json { render :json => @sighting,
                             :status => :created, :location => @sighting }
      else
        format.html { render :action => "new" }
        format.json { render :json => @sighting.errors,
                             :status => :unprocessable_entity }
      end
    end
  end

  def show
    @sighting = Sighting.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sightings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/index.html.erb
<%= link_to "New Sighting", new_sighting_path  %>

<h1>Sightings</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Location</th>
    <th>Sighting type</th>
    <th>Decription</th>
    <th>Seen by</th>
    <th>Comment</th>
    <th></th>
  </tr>

<% @sightings.each do |sighting| %>
  <tr>
    <td><%= sighting.date %></td>
    <td><%= sighting.location.name %></td>
    <td><%= sighting.sighting_type.name %></td>
    <td><%= sighting.description %></td>
    <td><%= sighting.sighter %></td>
    <td><%= sighting.comment %></td>
    <td><%= link_to 'Show', sighting %></td>
  </tr>
<% end %>
</table>

<br />

app/views/sightings/new.html.erb
<%= form_for(@sighting) do |form| %>
    <% if @sighting.errors.any? %>
        <div id="errorExplanation">
            <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited
                this sighting from being saved:</h2>
            <ul>
                <% @sighting.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :date %>
        <br/>
        <%= form.date_select :date %>
    </div>
    <%= form.fields_for :location do |location_form| %>
        <div class="field">
            <%= location_form.label :location %>
            <br/>
            <%= location_form.text_field :name %>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :sighting_type %>
        <br/>
        <%= form.collection_select :sighting_type_id, SightingType.all, :id, :name %>
    </div>
    <div class="field">
        <%= form.label :description %>
        <br/>
        <%= form.text_area :description %>
    </div>
    <div class="field">
        <%= form.label :seen_by %>
        <br/>
        <%= form.text_field :sighter %>
    </div>
    <div class="field">
        <%= form.label :comment %>
        <br/>
        <%= form.text_area :comment %>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @sighting.date %>
</p>

<p>
  <b>Location:</b>
  <%= @sighting.location.name %>
</p>

<p>
  <b>Sighting Type:</b>
  <%= @sighting.sighting_type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @sighting.description %>
</p>

<p>
  <b>Seen by:</b>
  <%= @sighting.sighter %>
</p>

<p>
  <b>Comment:</b>
  <%= @sighting.comment %>
</p>


<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>